
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Footer from '@/components/footer'
import Navbar from '@/components/Navbar'
import Authprovider from '@/components/AuthProvider/Authproviders'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'InDiBUS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='Container'>  
            <div className='Navbar'>     
               <Link href="/" className='exthe'><div className='flexconstent'><h3 className='in'>In</h3><h3 className='di'>Di</h3><h3 className='bus'>BUS</h3></div></Link>
             <div className='realnav'> <Navbar/></div>
            </div>
            <div className='item blank1'></div>
            
            <div className='item mainbody'>
              <Authprovider>{children}</Authprovider>
            </div>
            <div className='item blank2'> </div>
            <div className='item Footer'> <Footer/> </div>
        </div>
      
      </body>
    </html>
  )
}
