
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

import Authprovider from '@/components/AuthProvider/Authproviders'
import NextTopLoader from 'nextjs-toploader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'InDiBUS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) { 
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='Container'>  
        
            <div className='nav'>
             
            </div>
       
        </div>
      
      </body>
    </html>
  )
}
